config/routes.rb
Rails.application.routes.draw do
    root 'static_pages#root'

   resources :users, only: [:create, :new]
   resource :session, only: [:create, :new, :destroy]

   namespace :api, defaults: { format: :json } do
     resources :followings, only: [:create, :destroy]
     resources :groups, except: [:new, :edit]
     resources :posts, except: [:new, :edit] do
       member do
         post 'like',    to: 'posts#upvote'
         post 'dislike', to: 'posts#downvote'
         post 'unlike',    to: 'posts#unupvote'
         post 'undislike', to: 'posts#undownvote'
       end
     end
     resources :replies, except: [:new, :edit] do
       member do
         post 'like',    to: 'replies#upvote'
         post 'dislike', to: 'replies#downvote'
         post 'unlike',    to: 'replies#unupvote'
         post 'undislike', to: 'replies#undownvote'
       end
     end
   end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="#/"><img src="http://res.cloudinary.com/daqsrembo/image/upload/c_scale,h_50/v1434860778/Yeehaw-logo_2_lkkrh1.png" /></a>
    </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <% if signed_in? %>
          <li><a href="#/" title="Home">
            <span class="glyphicon glyphicon-home"></span>Home</a></li>
          <li><a href="#/groups/" title="Peek">
            <span class="glyphicon glyphicon-globe"></span>Peek</a></li>

          <li id='add-dropdown' class='dropdown'>
            <a href="#" class='dropdown-toggle' data-toggle='dropdown'
              role="button" aria-expanded="false" title="Me">
              <span class="glyphicon glyphicon-user"></span>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#/posts/">My Yeehaws</a></li>
              <li><a href="#/replies/">My Replies</a></li>
              <li role="separator" class="divider"></li>

              <li><a data-method="delete" href="<%= session_url %>" title="Signout">
                <span class="glyphicon glyphicon-log-out"></span>Signout</a></li>
            </ul>
          </li>

        <% else %>
          <li><a href="<%= new_session_url %>" title="Login">Login</a></li>
          <li><a href="<%= new_user_url %>" title="Sign up">Sign up</a></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<% if flash[:errors] %>
<div class="">
  <%= flash[:errors].join("<br>").html_safe %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yeehaw</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="http://www.yikyakapp.com/wp-content/themes/yik-yak-web-general/img/global/favicon.png">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" charset="utf-8">
    <% if (current_user) %>
      window.CURRENT_USER_ID = <%= current_user.id %>;
    <% end %>
  </script>
</head>
<body>

<%= render "layouts/header" %>
<%= yield %>

</body>
</html>